version: '3'

services:
  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    env_file:
      - ./components/config/.env
    volumes:
      - db:/data/postgres

  fastapi:
    container_name: fastapi_container
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./components/config/.env

  mlflow:
    container_name: mlflow_container
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./components/config/.env
    volumes:
      - mlflow:/mlflow

volumes:
  db:
  mlflow:
