version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
       - db:/data/postgres

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  db:
